version: '3.8'

name: PasswordManagerBE

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USERNAME: postgres
            POSTGRES_PASSWORD: postgres
            HOST: localhost
        ports:
            - "5432:5432"